root = "."
tmp_dir = "tmp"

[build]
include_ext = ["go"]
include_dir = ["cmd"]
cmd = "go build -ldflags \"-X main.version=$VERSION\" -o ./tmp/main ./cmd/..."
bin = "tmp/main"

[misc]
clean_on_exit = true
