# =================================================================
# An opinionated config for linting Go code with golangci-lint
# See https://golangci-lint.run/usage/linters/
# =================================================================

linters:
  enable:
    - revive # Replacement for golint
    - gofmt # Runs gofmt as part of the linter
    - gosec # Find security issues
    - wsl # Whitespace linter, very much an acquired taste
    - stylecheck # A few Go style rules
    - misspell # Find misspelled words
    - cyclop # Find cyclomatic complexity
    - gocyclo # Also find cyclomatic complexity
    - bodyclose # Check for HTTP body close errors
    - nilerr # Find bad nil/err handling
    - nilnil # Also find bad nil/err handling
    - tagliatelle # Find badly named struct tags

issues:
  exclude-files:
    # Test files are skipped, as they are Copilot generated
    - ".*_test\\.go$"

linters-settings:
  gosec:
    excludes:
      - G404
    config:
      global:
        nosec: true

  misspell:
    locale: UK # Enable UK spelling

  # Check struck tag naming
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: goCamel
        yaml: goCamel

  revive:
    severity: error
    enable-all-rules: false
    confidence: 0.5
    rules:
      # There are MANY rules you could enable...
      # See https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
      # And https://golangci-lint.run/usage/linters/#revive
      - name: line-length-limit
        severity: error
        arguments: [120]
      - name: var-naming
        severity: error
