# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"

      - name: Prepare
        run: make install-tools

      - name: Lint
        run: make lint

      - name: Unit Tests
        run: make test

      - name: Integration Tests
        run: make test-integration-report

      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report
        if: success() || failure()
        with:
          name: Integration Tests
          path: test-results.xml
          reporter: jest-junit

      - name: Build
        run: make build
